version: '3.8'

services:
  app:
    environment:
      - EMBEDDING_DEVICE=cpu
    deploy:
      resources:
        reservations:
          devices: []

  worker:
    environment:
      - EMBEDDING_DEVICE=cpu
    deploy:
      resources:
        reservations:
          devices: []

