"""add_whisper_config

Revision ID: 2b070af770e0
Revises: c3f6e9bef27c
Create Date: 2025-12-21 01:09:56.211287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b070af770e0'
down_revision = 'c3f6e9bef27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # Get database connection
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('user_preferences')]

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        if 'whisper_model' not in columns:
            batch_op.add_column(sa.Column('whisper_model', sa.String(length=50), nullable=False, server_default='base'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('whisper_model')

    # ### end Alembic commands ###
