"""add_llm_config

Revision ID: 6985c04b7d0a
Revises: 2b070af770e0
Create Date: 2025-12-21 01:44:16.615858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6985c04b7d0a'
down_revision = '2b070af770e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # Get database connection
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('user_preferences')]

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        if 'llm_provider' not in columns:
            batch_op.add_column(sa.Column('llm_provider', sa.String(length=50), nullable=False, server_default='lm_studio'))
        if 'openai_api_key' not in columns:
            batch_op.add_column(sa.Column('openai_api_key', sa.String(length=255), nullable=True))
        if 'anthropic_api_key' not in columns:
            batch_op.add_column(sa.Column('anthropic_api_key', sa.String(length=255), nullable=True))
        if 'local_llm_base_url' not in columns:
            batch_op.add_column(sa.Column('local_llm_base_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('local_llm_base_url')
        batch_op.drop_column('anthropic_api_key')
        batch_op.drop_column('openai_api_key')
        batch_op.drop_column('llm_provider')

    # ### end Alembic commands ###
