"""add_section_metadata

Revision ID: 9a8b7c6d5e4f
Revises: f8fe04793e92
Create Date: 2026-01-24 16:20:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a8b7c6d5e4f'
down_revision = '7c8d9e0f1g2h'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.drop_column('metadata_')

    # ### end Alembic commands ###
