"""add_metadata_gin_index

Revision ID: ad8c9e0f1g2h
Revises: 9a8b7c6d5e4f
Create Date: 2026-01-24 19:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8c9e0f1g2h'
down_revision = '9a8b7c6d5e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.create_index('ix_document_sections_metadata', ['metadata_'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.drop_index('ix_document_sections_metadata', postgresql_using='gin')

    # ### end Alembic commands ###
