"""add_source_section_id_to_hyper_edges

Revision ID: be9d0f1g2h3i
Revises: ad8c9e0f1g2h
Create Date: 2026-01-24 19:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be9d0f1g2h3i'
down_revision = 'ad8c9e0f1g2h'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding it
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Check if table exists first
    if 'hyper_edges' in inspector.get_table_names():
        columns = [c['name'] for c in inspector.get_columns('hyper_edges')]
        if 'source_section_id' not in columns:
            with op.batch_alter_table('hyper_edges', schema=None) as batch_op:
                batch_op.add_column(sa.Column('source_section_id', postgresql.UUID(as_uuid=True), nullable=True))
                batch_op.create_foreign_key(None, 'document_sections', ['source_section_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hyper_edges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_section_id')
    # ### end Alembic commands ###
