"""add_rag_settings

Revision ID: c3f6e9bef27c
Revises: 
Create Date: 2025-12-21 00:34:03.889867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f6e9bef27c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunk_size', sa.Integer(), nullable=False, server_default='512'))
        batch_op.add_column(sa.Column('chunk_overlap', sa.Integer(), nullable=False, server_default='512'))
        batch_op.add_column(sa.Column('selected_llm_model', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('selected_llm_model')
        batch_op.drop_column('chunk_overlap')
        batch_op.drop_column('chunk_size')

    # ### end Alembic commands ###
