"""add_ollama_num_ctx_fixed

Revision ID: f8fe04793e92
Revises: e5f6g7h8i9j0
Create Date: 2026-01-19 06:01:04.384859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fe04793e92'
down_revision = 'e5f6g7h8i9j0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('user_preferences')]

    if 'ollama_num_ctx' not in columns:
        with op.batch_alter_table('user_preferences', schema=None) as batch_op:
            batch_op.add_column(sa.Column('ollama_num_ctx', sa.Integer(), server_default='2048', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('ollama_num_ctx')

    # ### end Alembic commands ###
